### ISSUE TITLE
[FEATURE REQUEST] Add something to show the duration of the current task

### ISSUE THREAD

**Issue by can-I-do** [ttscoff/doing#129]
**Is your feature request related to a problem? Please describe.**
I want to have a small timer always showing me how long I am working on the current task. I also saw that is setting the start time in 12h and the 24h schema e.g. 2:23pm | Test smth new @done(2021-11-26 15:58)

sometimes I just want to know how long am I working on the task and right now I have to calculate :)

**Describe the solution you'd like**
> doing last -d(uration)
> 24min

that would make things easier to showcase your current task with how long you work on it in a gui or smth like that e.g:
![CleanShot 2021-11-27 at 17 03 06](https://user-images.githubusercontent.com/60129163/143688455-e5967961-dff7-4fbd-be99-643118c2c1e4.png)

but I want to add for 25mins

**Comment by ttscoff** [comment]
Your wish is my...

See the [most recent Changelog entry](https://github.com/ttscoff/doing/blob/master/CHANGELOG.md#212pre). This applies to the prerelease gem, so to try it out for now, you'll need to do `gem install doing --pre`. You should get 2.1.2pre or higher.

Basically you can add %duration to any template string. All display commands accept a --duration flag that will enable it to display elapsed time instead of the start-finish interval on unfinished entries. You can also just add `duration: true` to the config (either to root or to a specific template) and avoid using --duration on the command line. To change the display format from '00:01:24' to '1h 24m', set `interval_format: human` in config (again, in root or in a template).

Please give it a shot and let me know if that covers the bases for you.

**Comment by can-I-do** [comment]
oh, that is awesome!! 
it kind of works when I add it to a template, like last
`doing last Test out (at 12:04pm on Mon, since    0h 23m)`
but other than that I didn't  get it work, e.g. by providing --duration or adding it in a view
`  dur:
    section: Currently
    count: 1
    order: desc
    template: "%duration"
    tags_bool: NONE
    tags: done`
error: undefined method `[]' for nil:NilClass

btw can you add your own templates like:
`  last:
    date_format: "%-I:%M%P on %a"
    template: "%title (at %date, since %duration)%odnote"
    wrap_width: 88
  dur:
    date_format: "%-I:%M%P on %a"
    template: "%duration"
    wrap_width: 88`

and just call `doing dur` (doesnt work for me, maybe I am thinking wrong here.)

**Comment by can-I-do** [comment]
ah it is working like that in views! Thats enough for me!!! thanks so much!
`  btt:
    section: Currently
    count: 1
    order: desc
    template: "%title -%duration"
    tags_bool: NONE
    tags: done`
