### ISSUE TITLE
Can you share more info about what needs to be used to get templates displayed like in your examples

### ISSUE THREAD

**Issue by krzysiek-b** [ttscoff/doing#142]
Hi,
What I can see on your example is great
<img width="608" alt="image" src="https://user-images.githubusercontent.com/6192236/167313710-639e6ca0-f2ad-4728-88a1-44dcac8f80e4.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/6192236/167313747-c55b4bb0-fe10-41ae-affd-74218eaf9503.png">

What I get in reality on my Ubuntu on Windows (using windows terminal) is this 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/6192236/167313740-f326f0d2-724d-43ea-a948-4fb65ccbc42a.png">

The layout is different. The total table seems to be also formatted differently.

I'm not sure if this is just a Mac thing or just a font/terminal/shell you can share with us?
I would like to have similar resuts you have without having to buy a mac please ;)

**Comment by ttscoff** [comment]
The only notable differences between mine and yours are the font and colors and the totals formatting.

For font and color, I use JetBrains Mono and the Nord color palette in my terminal. I've changed my template string since that screenshot, but my current one is:

	template: "%reset%cyan%shortdate %boldwhite%80║ title %dark%boldmagenta[%boldwhite%-10section%boldmagenta]%reset
	      %yellow%interval%boldred%duration%dark%white%80_14│ note"

To get the box formatting on the totals block, try adding this to the root of your config:

	timer_format: human

(Or just run `doing config set timer_format human`)


Let me know if that helps!

-Brett

**Comment by krzysiek-b** [comment]
It helps, thank you :)
