### ISSUE TITLE
Support terminal title

### ISSUE THREAD

**Issue by mrjcleaver** [ttscoff/doing#65]
It would be nice if doing would support pushing the project and last task into the terminal title.

e.g. with https://github.com/mrjcleaver/terminal-title 

and/or with e.g.

PS1='[\e]1;\s\$ \W\a\e]2;\u@\h\a]'"$PS1"

**Comment by ttscoff** [comment]
That's a cool idea. Parsing the plain text file gets slow enough that a 
prompt_command that runs doing last would be horrible. You'd need to 
cache the last item or actually export $PS1 every time doing adds an 
entry, both of which are doable. I'll add it to the ideas list.

-Brett

**Comment by ttscoff** [comment]
Revisiting this: doing 2.0 now has hooks, so you can write a quick plugin to run scripts or perform actions any time the doing file is written, or even whenever an entry is added or modified, whatever suits your purposes. Different hooks receive different objects, but the recent content is readily available for parsing. You could have a post_entry_added hook that just wrote out the text of the entry to an environment variable as needed (though you'd have to be sure it was properly exported because it would be running in a protected process.)

See https://github.com/ttscoff/doing/wiki/Hooks#post_entry_added for some examples and details.
