### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by timford** [ttscoff/doing#68]
Could you make this available via homebrew, so OSX users can install with `brew install doing`?

**Comment by ttscoff** [comment]
Brew doesn't install gems. Mac users can just use 'gem install doing'. 

This is my iPhone. There are many like it, but this one is mine.

**Comment by ChristianBagley** [comment]
If you really _want_ to have the ability to install it via Homebrew, you could do so with `brew gem install doing`

Since `[brew-gem](https://github.com/sportngin/brew-gem)` manages Ruby Gems as Homebrew formulas. 

But really it is just added steps. Like Bret said, using `gem install` is the most straight-forward method.
