### ISSUE TITLE
--back error with 1.0.8pre

### ISSUE THREAD

**Issue by Jestre** [ttscoff/doing#86]
I discovered this software yesterday and installed it to try.  I configured the basics per the docs, but when I try to add an entry with the `--back` argument, I get weird results, e.g.

I entered the following about 6:30 pm yesterday (3/11):

> doing now --back 10m Working with Chris and Dwayne on 25114

and got this in the file (date and time wrong):

> - 2016-03-10 00:00 | Working with Chris and Dwayne on 25114

Entered this today (3/12) at about 0630:

> doing now Checked VZW usage --back 20m

and got this (date and time):

> - 2016-03-20 00:00 | Took dogs out, checked VZW usage @done(2016-03-12 06:59)

Obviously for that one, `doing done` worked as expected, but it seems `--back` is taking the back time and using it in the day (dd) field and then using 00:00 as the time, rather than computing now-backtime, e.g. `--back 20m` yields a date of yyyy-mm-20.

Do I have something misconfigured?  Or is this functionality still incomplete in the pre version?

Thank you,

Scott

Ruby: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15](installed via RVM)
OS: El Capitan
Gem: doing (1.0.8pre)

**Comment by ttscoff** [comment]
Just tested and it does look like that feature is broken pretty badly. 
I'll try to put some time into figuring that out this weekend.

-Brett

**Comment by zug-zug** [comment]
FWIW, I think the bug is here: https://github.com/ttscoff/doing/blob/master/lib/doing/wwid.rb#L282-L284

Seems like `Time.parse` will succeed for *some* values of `input` which use hour/day/minute notation (e.g. `20m`), so rescuing the exception isn't enough of a guard.

Specifically, `Time.parse` succeeds when input format looks like:
* `Xh` for `X` in [-24, 24]
* `Xm` and `Xd` for `X` in [-10, -31] and [10, 31]
* `0hXm` for `X < 60`
* `yesterday 5:30pm`

`Time.parse` is insufferable! :P
